version: '3'
services:
    # scrapper:
    #     build: .
    neo4j:
      image: neo4j:3.3
      # volumes:
      #  - ./plugins:/var/lib/neo4j/plugins # Mount the plugins to the plugin folder
      #  - ./conf:/var/lib/neo4j/conf # security configs
      ports:
       - "7474:7474"
       - "7687:7687"
      environment:
       - NEO4J_AUTH=neo4j/123456 # configure the instance with custom username/password
       - NEO4J_HEAP_MEMORY=2048 # configure the heap memory
       - NEO4J_CACHE_MEMORY=1G # configure the cache memory
      ulimits:
        nproc: 40000
        nofile:
            soft: 40000
            hard: 40000
